### ISSUE TITLE
Allow custom list

### ISSUE THREAD

**Issue by SamVerschueren** [kevva/viewport-list#8]
Currently, we retrieve the list from http://viewportsizes.com/devices.json. But this list doesn't seem to be maintained very well.

In order to fix this, we should be able to extend this list. So as we suggested in #7, we should create a custom JSON list that gets merged together with the list from viewportsizes.com when the list is being rebuilt (`node make.js`).

Suggestions for the name of the custom data file?

- custom-data.json
- data-custom.json
- custom-viewportsizes.com
- ...

**Comment by kevva** [comment]
Fixed in https://github.com/kevva/viewport-list/commit/5d7b61737c03b695c4e3369c250bd629411705f9. Didn't see you created an issue for this. Anyway, I named it `custom.json`, feel free to change it if you find another name suitable :).

**Comment by SamVerschueren** [comment]
Now we have 2 separate files. Shouldn't we merge both files in `make.js` instead and offer one file (`data.json`)? The user of this module doesn't need to know where the data comes from.

> Feel free to change it if you find another name suitable :).

I'm good :)

**Comment by kevva** [comment]
> Shouldn't we merge both files in make.js instead and offer one file (data.json)?

That's a good idea!
